# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.srcs/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/design_1_OneDCFNN_IP_0_2.xci
# IP: The module: 'design_1_OneDCFNN_IP_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/df_output_buffer/df_output_buffer.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==df_output_buffer || ORIG_REF_NAME==df_output_buffer} -quiet] -quiet

# IP: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/df_mult/df_mult.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==df_mult || ORIG_REF_NAME==df_mult} -quiet] -quiet

# IP: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/fr_feature_map_buffer/fr_feature_map_buffer.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fr_feature_map_buffer || ORIG_REF_NAME==fr_feature_map_buffer} -quiet] -quiet

# IP: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/fc_feature_map_buffer/fc_feature_map_buffer.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fc_feature_map_buffer || ORIG_REF_NAME==fc_feature_map_buffer} -quiet] -quiet

# IP: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/fc_mult/fc_mult.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fc_mult || ORIG_REF_NAME==fc_mult} -quiet] -quiet

# IP: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/bn_feature_map_buffer/bn_feature_map_buffer.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bn_feature_map_buffer || ORIG_REF_NAME==bn_feature_map_buffer} -quiet] -quiet

# IP: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/bn_mult/bn_mult.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bn_mult || ORIG_REF_NAME==bn_mult} -quiet] -quiet

# IP: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/mp_feature_map_buffer/mp_feature_map_buffer.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mp_feature_map_buffer || ORIG_REF_NAME==mp_feature_map_buffer} -quiet] -quiet

# IP: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/conv_feature_map_buffer/conv_feature_map_buffer.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_feature_map_buffer || ORIG_REF_NAME==conv_feature_map_buffer} -quiet] -quiet

# IP: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/conv_mult/conv_mult.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_mult || ORIG_REF_NAME==conv_mult} -quiet] -quiet

# IP: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/input_signal/input_signal.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==input_signal || ORIG_REF_NAME==input_signal} -quiet] -quiet

# XDC: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/df_output_buffer/df_output_buffer_ooc.xdc

# XDC: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/fr_feature_map_buffer/fr_feature_map_buffer_ooc.xdc

# XDC: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/fc_feature_map_buffer/fc_feature_map_buffer_ooc.xdc

# XDC: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/bn_feature_map_buffer/bn_feature_map_buffer_ooc.xdc

# XDC: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/mp_feature_map_buffer/mp_feature_map_buffer_ooc.xdc

# XDC: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/conv_feature_map_buffer/conv_feature_map_buffer_ooc.xdc

# XDC: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/input_signal/input_signal_ooc.xdc

# IP: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.srcs/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/design_1_OneDCFNN_IP_0_2.xci
# IP: The module: 'design_1_OneDCFNN_IP_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/df_output_buffer/df_output_buffer.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==df_output_buffer || ORIG_REF_NAME==df_output_buffer} -quiet] -quiet

# IP: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/df_mult/df_mult.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==df_mult || ORIG_REF_NAME==df_mult} -quiet] -quiet

# IP: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/fr_feature_map_buffer/fr_feature_map_buffer.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fr_feature_map_buffer || ORIG_REF_NAME==fr_feature_map_buffer} -quiet] -quiet

# IP: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/fc_feature_map_buffer/fc_feature_map_buffer.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fc_feature_map_buffer || ORIG_REF_NAME==fc_feature_map_buffer} -quiet] -quiet

# IP: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/fc_mult/fc_mult.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fc_mult || ORIG_REF_NAME==fc_mult} -quiet] -quiet

# IP: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/bn_feature_map_buffer/bn_feature_map_buffer.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bn_feature_map_buffer || ORIG_REF_NAME==bn_feature_map_buffer} -quiet] -quiet

# IP: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/bn_mult/bn_mult.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bn_mult || ORIG_REF_NAME==bn_mult} -quiet] -quiet

# IP: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/mp_feature_map_buffer/mp_feature_map_buffer.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mp_feature_map_buffer || ORIG_REF_NAME==mp_feature_map_buffer} -quiet] -quiet

# IP: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/conv_feature_map_buffer/conv_feature_map_buffer.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_feature_map_buffer || ORIG_REF_NAME==conv_feature_map_buffer} -quiet] -quiet

# IP: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/conv_mult/conv_mult.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==conv_mult || ORIG_REF_NAME==conv_mult} -quiet] -quiet

# IP: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/input_signal/input_signal.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==input_signal || ORIG_REF_NAME==input_signal} -quiet] -quiet

# XDC: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/df_output_buffer/df_output_buffer_ooc.xdc

# XDC: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/fr_feature_map_buffer/fr_feature_map_buffer_ooc.xdc

# XDC: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/fc_feature_map_buffer/fc_feature_map_buffer_ooc.xdc

# XDC: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/bn_feature_map_buffer/bn_feature_map_buffer_ooc.xdc

# XDC: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/mp_feature_map_buffer/mp_feature_map_buffer_ooc.xdc

# XDC: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/conv_feature_map_buffer/conv_feature_map_buffer_ooc.xdc

# XDC: e:/Zedboard/1DCFNN/1DCFNN_SYSTEM/1DCFNN_SYSTEM.gen/sources_1/bd/design_1/ip/design_1_OneDCFNN_IP_0_2/src/input_signal/input_signal_ooc.xdc
