# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Zedboard/1DCFNN/project_1/project_1.srcs/sources_1/ip/input_signal/input_signal.xci
# IP: The module: 'input_signal' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Zedboard/1DCFNN/project_1/project_1.gen/sources_1/ip/input_signal/input_signal_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'input_signal'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/Zedboard/1DCFNN/project_1/project_1.srcs/sources_1/ip/input_signal/input_signal.xci
# IP: The module: 'input_signal' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Zedboard/1DCFNN/project_1/project_1.gen/sources_1/ip/input_signal/input_signal_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'input_signal'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
