# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Zedboard/1DCFNN/1DCFNN/1DCFNN.srcs/sources_1/ip/conv_feature_map_buffer/conv_feature_map_buffer.xci
# IP: The module: 'conv_feature_map_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/zedboard/1dcfnn/project_1/project_1.tmp/cfnn_ip_v1_0_project/CFNN_IP_v1_0_project.gen/sources_1/ip/conv_feature_map_buffer/conv_feature_map_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'conv_feature_map_buffer'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/Zedboard/1DCFNN/1DCFNN/1DCFNN.srcs/sources_1/ip/conv_feature_map_buffer/conv_feature_map_buffer.xci
# IP: The module: 'conv_feature_map_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/zedboard/1dcfnn/project_1/project_1.tmp/cfnn_ip_v1_0_project/CFNN_IP_v1_0_project.gen/sources_1/ip/conv_feature_map_buffer/conv_feature_map_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'conv_feature_map_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
