# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/df_mult/df_mult.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==df_mult || ORIG_REF_NAME==df_mult} -quiet] -quiet

# IP: ip/fc_mult/fc_mult.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fc_mult || ORIG_REF_NAME==fc_mult} -quiet] -quiet

# IP: ip/input_signal/input_signal.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==input_signal || ORIG_REF_NAME==input_signal} -quiet] -quiet

# XDC: e:/zedboard/1dcfnn/project_1/project_1.tmp/cfnn_ip_v1_0_project/CFNN_IP_v1_0_project.gen/sources_1/ip/input_signal/input_signal_ooc.xdc
